# 服务端端口配置
server:
  port: 10001

# 日志配置
logging:
  # 输出等级配置
  level:
    # 默认为info
    root: info
    # vteam包为debug
    com.vteam: debug
  # 日志文件路径
  file:
    name:  ${application.deployPath}${spring.application.name}/logs/${spring.application.name}-${server.port}.log

management:
  endpoints:
    enabled-by-default: false

# Spring配置
spring:
  main:
    # 是否允许覆盖注册服务
    allow-bean-definition-overriding: true
    # 是否允许循环引用
    allow-circular-references: true

  # 自己加的配置
  profiles:
    active:
  # 实例名称
  application:
    name: basedev
    url:
  # 数据源配置
  datasource:
    name: nfms
    url: jdbc:mysql://192.168.10.145:3306/nfms?useSSL=false&characterEncoding=utf8
    username: root
    password: ipu123
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # 连接超时时间
      connection-timeout: 3000
      # 最小连接数
      minimum-idle: 1
      # 最大连接数
      maximum-pool-size: 2
      # 自动提交
      auto-commit: true
      # 最大连接时长
      idle-timeout: 60000
      # 连接存活时长
      max-lifetime: 28740000
      # 测试连接SQL
      connection-test-query: SELECT 1 FROM DUAL
  # ActiveMQ配置
  activemq:
    # ActiveMQ开关
    switch: true
    # ActiveMQ服务器地址
    broker-url: tcp://192.168.121.222:61616
    # ActiveMQ服务器用户名，密码
    user: admin
    password: admin
    pool:
      enabled: false
    # 队列
    queueName:
      # 微信发送器
      weixinSender: wx-${spring.profiles.active}-${spring.application.name}
      # 消息
      message: message-${spring.application.name}-${spring.profiles.active}
      # 推送数据发送
      pushData: smme-pushData-${spring.profiles.active}-
      # 推送数据接收
      pushDataConsumer: smme-pushData-${spring.profiles.active}-${application.brandCode}
    # 发布者
    topic:
      # websocket 消息发布
      ws-topic: ws-${spring.profiles.active}-${spring.application.name}
      # Lucene
      lucene-topic: lucene-${spring.profiles.active}-${spring.application.name}
  # 邮箱配置
  mail:
    default-encoding: UTF-8
    port: 25
    protocol: smtp
    host: smtp.hnkhj.com.cn
    username: service.cn
    password: Sghdr$36#
    sendmail: service@hnkhj.com.cn
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: false
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
  # 动态模板配置
  thymeleaf:
    encoding: UTF-8
    mode: HTML
    servlet:
      content-type: text/html
    cache: false
    prefix: classpath:/templates/html/
    suffix: .html
  # freemarker配置
  freemarker:
    charset: UTF-8
    template-loader-path:
    prefer-file-system-access: false
    cache: false
  # redis 配置
  data:
    redis:
      host: 192.168.122.28
      password: Redis@123456
      database: 10
  # 项目配置
  vtarm:
    developer-mode: false
    filter:
      ignore-url: /smews
    security:
      level: high
      ignore-urls: /favicon.ico,/public/**,/anon/**,/common/**,/operation/**,/homeCommon/**,/file/**,/library/**,/sys/login,/sys/logout,/authz/doResetPassword,/console/**,/customInfo/**,/projectCommon/**,/statistics/**,/home/**,/weixin/**
      allow-replay-urls: [ "/console/**","/operation/**","/templates/**","/file/**","/sys/login","/sys/logout", "/actuator**", "/favicon.ico" ]
      # 登录会话(access_token)有效时长(分钟) 一天=60*24*1=1440
      timeToLive: 1440
    # 编解码配置
    codec:
      api-enable: false
      db-enable: true
      aes-key: bWFsbHB3ZA==WNST
      aes-iv: 1234567890123456
      ignore-url: ["/external/bill/**", "/businessService","/wxmsgpush/getWxUrl/**"]
    # OCR配置(百度)
    ocr:
      enable: true
      app-id: 11750458
      api-key: xmqNUbccxbaPNqaBokpHhZDG
      secret-key: tZPGYhjdl4NdjolZctDtFlKOdpjKBOqM
    # 定时任务配置
    task:
      crons:
        # 同步序列任务
        synchronizeSequenceJob: 0 0 0 1/1 * ?
    transaction:
      timeout: 60
    sql:
      type: mysql
    actuator:
      username: ${spring.application.name}
      password: actuator@-${spring.application.name}

# mybatis
mybatis-plus:
  mapperLocations: classpath*:/mappers/**/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.vteam.cars.entity.model
  global-config:
    # 刷新mapper 调试神器
    refresh: true
    # 数据库相关配置
    db-config:
      # 驼峰下划线转换
      column-underline: true
      # 逻辑删除配置（下面3个配置）
      logic-delete-value: 1
      logic-not-delete-value: 0
      # 主键类型
      id-type: input
      # 字段策略
      field-strategy: not_empty
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: 'null'
    # 输出到控制台
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 输出到日志文件
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

plugin:
  htmlConvertToPDFPluginPath: E:/wkhtmltopdf/bin/wkhtmltopdf

# 应用配置
application:
  # 首页类型（1表示完整版/2表示简版）
  portalIndexType: 1
  # 部署路径
  deployPath: F:/tmp/
  # 字符集编码
  encoding: UTF-8
  # 数据库类型 MYSQL ORACLE DB2 SQLSERVER
  dbType: MYSQL
  # 开发者模式（1=开启/0=关闭）
  developer-mode: 0
  # 文件相关配置
  file:
    # 显示大文件分块上传时的合并文件线程数
    storage:
      threads: 100
    # 启用模式[local=本地仓库/filecenter=文件中心]
    # active: filecenter
    active: local
    # 文件仓库路径
    repositoryPath: ${application.deployPath}${spring.application.name}/file/
    # 临时文件存放路径
    tmpPath: ${application.deployPath}${spring.application.name}/tmp/
    # lucen索引保存文件路径
    lucenePath: ${application.deployPath}${spring.application.name}/lucene/
    # 模板
    templates:
      # 导入模板路径
      importPath: /templates/import/
      # 导出模板路径
      exportPath: /templates/export/
      # 上传模板路径
      archivePath: /templates/archives/
      # 水印图片路径
      watermark: /static/images/watermark

  # 安控
  security:
    # 登录最大尝试次数
    maxRetryTotal: 5
    # 用户锁定时间（小时）
    lockedHours: 2
    # 登录会话(access_token)有效时长(秒)-暂无用,使用spring.vtarm.security.timeToLive
    timeToLive: 1800
    # 每个用户单个接口的调用间隔时长控制（秒）
    userAccessMinTime: 60

  # 远程调用配置
  remote:
    config:
      # 连接超时或异常重试次数
      retryTime: 3
      # 长连接保持时间，单位为s
      keepAliveTime: 30
      # 连接池最大连接数&每个路由最大连接数
      connMaxTotal: 200
      maxPerRoute: 50
      # 连接超时时间，单位ms
      connectTimeout: 12000
      # 请求超时时间
      connectRequestTimeout: 12000
      # sock超时时间
      socketTimeout: 20000
      # 连接存活时间，单位s
      timeToLive: 60

  # 短信服务接口配置
  sms:
    # 短信服务[sxt=闪信通/wxt=沃讯通/alisms=阿里云短信服务]
    active: alisms


  # 缓存模式[ram=内存/redis=redis缓存数据库]
  cache:
    mode: redis
